spring:
  application:
    name: SportBot
  cloud:
    gcp:
      sql:
        database-name: sportbot_db
        instance-connection-name: sportbot-485510:europe-west1:sportbotdb
  datasource:
    username: postgres
    password: sportbotDb1_
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml